import mongoose from 'mongoose'
import dotenv from 'dotenv'
import Destination from './models/Destination.js'
import Tour from './models/Tour.js'
import Species from './models/Species.js'

dotenv.config({ path: '../.env'})

const destinations = [
  {
    name: 'Baja California',
    tagline: 'Where Giants of the Deep Come to Breathe',
    region: 'Americas',
    category: 'Ocean',
    country: 'Mexico',
    description: 'The nutrient-rich waters of Baja California create one of the world\'s greatest whale watching destinations. Every winter, blue and grey whales migrate here to breed in the warm lagoons.',
    longDescription: 'Stretching over 1,200 kilometres along Mexico\'s Pacific coast, Baja California is a narrow peninsula of extraordinary ecological richness. The convergence of cold California Current and warm tropical waters creates a marine buffet that attracts the largest animals ever to have existed on Earth. The grey whale lagoons of Scammon, San Ignacio, and Magdalena Bay are UNESCO-protected sanctuaries where whales come so close to small boats that you can hear them breathe.',
    images: [
      'https://images.unsplash.com/photo-1568430462989-44163eb1752f?w=1200',
      'https://images.unsplash.com/photo-1614729939124-032d1e6c9945?w=1200',
    ],
    bestSeason: 'December to April',
    highlights: ['Blue whale sightings', 'Grey whale breeding lagoons', 'Sea of Cortez diving', 'Desert-meets-ocean landscapes', 'Dolphin superpods'],
    wildlife: ['Blue Whale', 'Grey Whale', 'Humpback Whale', 'Orca', 'Bottlenose Dolphin'],
    difficulty: 'Easy',
    isFeatured: true,
  },
  {
    name: 'Great Barrier Reef',
    tagline: 'The Living Masterpiece Beneath the Surface',
    region: 'Oceania',
    category: 'Ocean',
    country: 'Australia',
    description: 'The world\'s largest coral reef system, stretching over 2,300 kilometres, is home to an astonishing diversity of marine life including sea turtles, reef sharks, and thousands of fish species.',
    longDescription: 'Visible from outer space, the Great Barrier Reef is Earth\'s most complex natural ecosystem. Composed of over 2,900 individual reefs and 900 islands, it supports more than 1,500 species of fish, 4,000 types of mollusc, and six of the world\'s seven species of sea turtle. Snorkelling or diving here is like entering another dimension — one of colour, silence, and ancient biological wonder.',
    images: [
      'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=1200',
      'https://images.unsplash.com/photo-1583212292454-1fe6229603b7?w=1200',
    ],
    bestSeason: 'June to October',
    highlights: ['Coral garden snorkelling', 'Sea turtle encounters', 'Reef shark diving', 'Whale shark season', 'Island camping'],
    wildlife: ['Manta Ray', 'Great White Shark', 'Humpback Whale', 'Green Sea Turtle', 'Whale Shark'],
    difficulty: 'Easy',
    isFeatured: true,
  },
  {
    name: 'Amazon River Basin',
    tagline: 'The Lungs of the Earth, The Heart of Life',
    region: 'Americas',
    category: 'River',
    country: 'Brazil',
    description: 'The Amazon is the world\'s greatest river ecosystem — a vast, labyrinthine network of waterways that shelters more species per square kilometre than anywhere else on Earth.',
    longDescription: 'The Amazon River discharges more water into the ocean than the next seven largest rivers combined. Its basin covers 40% of South America and contains one in ten of all known species on Earth. Navigating its dark, tannin-stained tributaries by canoe, you enter a world where pink river dolphins surface alongside your boat, caimans watch from the banks, and the jungle canopy closes overhead like a cathedral.',
    images: [
      'https://images.unsplash.com/photo-1614531341773-3bff8b7cb3fc?w=1200',
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200',
    ],
    bestSeason: 'June to November',
    highlights: ['Pink river dolphin encounters', 'Night canoe expeditions', 'Canopy walkways', 'Indigenous community visits', 'Piranha fishing'],
    wildlife: ['Giant River Otter', 'Jaguar', 'Pink River Dolphin', 'Green Anaconda', 'Harpy Eagle'],
    difficulty: 'Moderate',
    isFeatured: true,
  },
  {
    name: 'Norwegian Fjords',
    tagline: 'Ancient Ice, Living Waters, Wild Orcas',
    region: 'Europe',
    category: 'Mountain',
    country: 'Norway',
    description: 'Norway\'s dramatic fjords carve deep into the mountains, creating sheltered waters where orca pods hunt herring in winter and humpback whales breach against a backdrop of snow-capped peaks.',
    longDescription: 'Carved by glaciers over millions of years, Norway\'s fjords are among Earth\'s most dramatic landscapes. The Vestfjorden and Tysfjord regions attract large concentrations of orca and humpback whales during the winter herring season — an extraordinary spectacle of nature\'s raw power. Above the water, the landscape is equally breathtaking: sheer cliff faces dropping hundreds of metres into still, dark water.',
    images: [
      'https://images.unsplash.com/photo-1531366936337-7c912a4589a7?w=1200',
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200',
    ],
    bestSeason: 'October to February',
    highlights: ['Orca pod encounters', 'Northern lights at sea', 'Fjord kayaking', 'Humpback whale breaching', 'Midnight sun sailing'],
    wildlife: ['Orca', 'Humpback Whale', 'Atlantic Puffin', 'White-tailed Eagle', 'Arctic Fox'],
    difficulty: 'Moderate',
    isFeatured: true,
  },
  {
    name: 'Serengeti Plains',
    tagline: 'Where the Earth Still Moves with Life',
    region: 'Africa',
    category: 'Forest',
    country: 'Tanzania',
    description: 'The Serengeti hosts the greatest wildlife spectacle on Earth — the annual Great Migration of over two million wildebeest, zebra, and gazelle across its endless golden plains.',
    longDescription: 'The name Serengeti comes from the Maasai word meaning "endless plains" — and endless it feels. This 30,000 square kilometre ecosystem supports the highest density of large mammals on Earth. Predators abound: lion prides sprawl across termite mounds, cheetahs scan from rocky outcrops, and leopards drape themselves over acacia branches. The Great Migration, the largest overland animal movement on the planet, passes through here between July and October.',
    images: [
      'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=1200',
      'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=1200',
    ],
    bestSeason: 'June to October',
    highlights: ['Great Migration crossing', 'Big Five encounters', 'Hot air balloon safari', 'Night game drives', 'Maasai cultural experience'],
    wildlife: ['African Lion', 'Leopard', 'African Elephant', 'Cheetah', 'Nile Crocodile'],
    difficulty: 'Easy',
    isFeatured: false,
  },
  {
    name: 'Galápagos Islands',
    tagline: 'Evolution\'s Living Laboratory',
    region: 'Americas',
    category: 'Ocean',
    country: 'Ecuador',
    description: 'These remote volcanic islands inspired Darwin\'s theory of evolution and remain one of the world\'s most pristine wildlife sanctuaries, where animals have no fear of humans.',
    longDescription: 'Located 1,000 kilometres off Ecuador\'s Pacific coast, the Galápagos Islands are the closest place on Earth to paradise for a naturalist. The wildlife here — having evolved in isolation with no natural predators — shows no fear of humans whatsoever. Marine iguanas swim alongside snorkellers, blue-footed boobies perform mating dances at arm\'s length, and Galápagos sea lions use tourists as pillows. Beneath the water, whale sharks, hammerheads, and manta rays patrol in surreal abundance.',
    images: [
      'https://images.unsplash.com/photo-1544979590-37e9b47eb705?w=1200',
      'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=1200',
    ],
    bestSeason: 'December to May',
    highlights: ['Marine iguana snorkelling', 'Giant tortoise sanctuary', 'Blue-footed booby watching', 'Hammerhead shark diving', 'Darwin Research Station'],
    wildlife: ['Manta Ray', 'Galápagos Penguin', 'Marine Iguana', 'Whale Shark', 'Blue-footed Booby'],
    difficulty: 'Easy',
    isFeatured: false,
  },
  {
    name: 'Antarctic Peninsula',
    tagline: 'The Last Great Wilderness',
    region: 'Antarctica',
    category: 'Arctic',
    country: 'Antarctica',
    description: 'Antarctica is Earth\'s final frontier — a vast, pristine continent of ice and silence where fin whales, orcas, and millions of penguins exist in a world untouched by modern civilisation.',
    longDescription: 'The Antarctic Peninsula is the most wildlife-rich part of the world\'s most remote continent. In summer, the seas teem with krill — the foundation of a food web that sustains blue whales, fin whales, leopard seals, and five species of penguin. Landing on the continent itself is a profound experience: the silence, the scale, and the sheer wildness of the place create a humility that stays with you forever.',
    images: [
      'https://images.unsplash.com/photo-1517825738774-7de9363ef735?w=1200',
      'https://images.unsplash.com/photo-1494500764479-0c8f2919a3d8?w=1200',
    ],
    bestSeason: 'November to March',
    highlights: ['Emperor penguin colonies', 'Iceberg kayaking', 'Fin whale encounters', 'Polar plunge', 'Zodiac wildlife cruises'],
    wildlife: ['Emperor Penguin', 'Fin Whale', 'Orca', 'Leopard Seal', 'Albatross'],
    difficulty: 'Challenging',
    isFeatured: false,
  },
  {
    name: 'Scottish Highlands',
    tagline: 'Raw, Ancient and Untamed',
    region: 'Europe',
    category: 'Mountain',
    country: 'Scotland',
    description: 'The Scottish Highlands offer a hauntingly beautiful wilderness of mist-covered mountains, dark lochs, and ancient forests where red deer, golden eagles, and otters roam freely.',
    longDescription: 'The Scottish Highlands are one of Europe\'s last great wild places. Vast and sparsely populated, the landscape has a brooding, primeval quality — mountains cloaked in heather, rivers running black with peat, and skies that change from silver to gold in minutes. The Cairngorms National Park, Britain\'s largest, shelters ospreys, red squirrels, and rare mountain hares. The sea lochs of the west coast are home to otters, harbour porpoises, and occasionally minke whales.',
    images: [
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200',
      'https://images.unsplash.com/photo-1573108724029-4c46571d6490?w=1200',
    ],
    bestSeason: 'May to September',
    highlights: ['Golden eagle spotting', 'Red deer stalking', 'Otter watching at dusk', 'Loch wild swimming', 'Highland whisky trail'],
    wildlife: ['Red Deer', 'Golden Eagle', 'European Otter', 'Red Squirrel', 'Osprey'],
    difficulty: 'Moderate',
    isFeatured: false,
  },
]

const species = [
  {
    name: 'Blue Whale',
    scientificName: 'Balaenoptera musculus',
    habitat: 'Ocean',
    conservationStatus: 'Endangered',
    description: 'The blue whale is the largest animal ever known to have existed on Earth. A single heartbeat from its basketball-sized heart can be heard from two miles away. Despite their immense size, they feed almost exclusively on tiny krill, consuming up to 40 million of them each day.',
    image: 'https://images.unsplash.com/photo-1568430462989-44163eb1752f?w=1200',
    funFact: 'A blue whale\'s heart is the size of a small car and can be heard from 2 miles away underwater.',
    foundAt: ['Baja California', 'Antarctic Peninsula'],
    characteristics: {
      weight: 'Up to 200 tonnes',
      length: 'Up to 33 metres',
      lifespan: '80-90 years',
      diet: 'Krill exclusively',
    },
    isFeatured: true,
  },
  {
    name: 'Humpback Whale',
    scientificName: 'Megaptera novaeangliae',
    habitat: 'Ocean',
    conservationStatus: 'Least Concern',
    description: 'Famous for their haunting, complex songs that can last for hours and travel thousands of kilometres through the ocean, humpback whales are among the most acrobatic of all whale species. Their spectacular breaches — launching their full 40-tonne body out of the water — are one of nature\'s most breathtaking sights.',
    image: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=1200',
    funFact: 'Humpback whale songs evolve over time — whales in the same ocean all gradually change their song together, like a cultural trend.',
    foundAt: ['Baja California', 'Norwegian Fjords', 'Great Barrier Reef'],
    characteristics: {
      weight: 'Up to 40 tonnes',
      length: 'Up to 16 metres',
      lifespan: '45-100 years',
      diet: 'Krill and small fish',
    },
    isFeatured: true,
  },
  {
    name: 'Orca',
    scientificName: 'Orcinus orca',
    habitat: 'Ocean',
    conservationStatus: 'Near Threatened',
    description: 'The most powerful predator in the ocean, orcas are highly intelligent, intensely social animals that live in tight family groups led by elder females. Different orca populations have developed unique hunting cultures — some beach themselves to catch seals, others use coordinated wave-washing techniques, and some specialise entirely in hunting other whales.',
    image: 'https://images.unsplash.com/photo-1544979590-37e9b47eb705?w=1200',
    funFact: 'Each orca pod has its own unique dialect of calls — they can identify family members by their distinctive vocalisations.',
    foundAt: ['Norwegian Fjords', 'Baja California', 'Antarctic Peninsula'],
    characteristics: {
      weight: 'Up to 6 tonnes',
      length: 'Up to 9 metres',
      lifespan: '50-90 years',
      diet: 'Fish, seals, sharks, other whales',
    },
    isFeatured: true,
  },
  {
    name: 'Sperm Whale',
    scientificName: 'Physeter macrocephalus',
    habitat: 'Ocean',
    conservationStatus: 'Vulnerable',
    description: 'The largest toothed animal on Earth, the sperm whale dives deeper than almost any other mammal — plunging over 3,000 metres into complete darkness in search of giant squid. Its enormous head contains the largest brain of any animal that has ever lived.',
    image: 'https://images.unsplash.com/photo-1614729939124-032d1e6c9945?w=1200',
    funFact: 'Sperm whales can hold their breath for over 90 minutes and dive deeper than 3,000 metres to hunt giant squid in complete darkness.',
    foundAt: ['Baja California', 'Galápagos Islands'],
    characteristics: {
      weight: 'Up to 57 tonnes',
      length: 'Up to 20 metres',
      lifespan: '70 years',
      diet: 'Giant squid, large fish',
    },
    isFeatured: true,
  },
  {
    name: 'Fin Whale',
    scientificName: 'Balaenoptera physalus',
    habitat: 'Ocean',
    conservationStatus: 'Vulnerable',
    description: 'The second largest animal on Earth after the blue whale, the fin whale is built for speed — capable of sustained bursts of 37 km/h, earning it the nickname "the greyhound of the sea." Its asymmetric colouring, with a white right jaw and dark left jaw, is unique among all living creatures.',
    image: 'https://images.unsplash.com/photo-1531366936337-7c912a4589a7?w=1200',
    funFact: 'The fin whale is the only animal on Earth with asymmetric colouring — its right jaw is white and its left jaw is dark.',
    foundAt: ['Antarctic Peninsula', 'Norwegian Fjords'],
    characteristics: {
      weight: 'Up to 74 tonnes',
      length: 'Up to 27 metres',
      lifespan: '80-90 years',
      diet: 'Krill, squid, small schooling fish',
    },
    isFeatured: false,
  },
  {
    name: 'Narwhal',
    scientificName: 'Monodon monoceros',
    habitat: 'Arctic',
    conservationStatus: 'Near Threatened',
    description: 'The unicorn of the sea, the narwhal\'s distinctive spiral tusk is actually a sensory organ — a giant tooth containing millions of nerve endings that can detect changes in water temperature, pressure, and salinity. They are among the deepest-diving Arctic mammals, reaching depths of 1,500 metres.',
    image: 'https://images.unsplash.com/photo-1494500764479-0c8f2919a3d8?w=1200',
    funFact: 'The narwhal\'s tusk is a sensory organ with 10 million nerve endings — it can sense changes in water temperature, salinity, and pressure.',
    foundAt: ['Antarctic Peninsula'],
    characteristics: {
      weight: 'Up to 1.6 tonnes',
      length: 'Up to 5.5 metres (plus tusk)',
      lifespan: '50 years',
      diet: 'Arctic cod, squid, shrimp',
    },
    isFeatured: true,
  },
  {
    name: 'Manta Ray',
    scientificName: 'Mobula birostris',
    habitat: 'Ocean',
    conservationStatus: 'Vulnerable',
    description: 'The largest ray in the world, the oceanic manta ray glides through tropical waters with a grace that seems almost supernatural. Despite their enormous size — wingspans reaching 7 metres — they feed exclusively on microscopic plankton, filter-feeding as they loop through the water in elegant spirals.',
    image: 'https://images.unsplash.com/photo-1583212292454-1fe6229603b7?w=1200',
    funFact: 'Manta rays have the largest brain-to-body ratio of any fish and are one of the few animals that can recognise themselves in a mirror.',
    foundAt: ['Great Barrier Reef', 'Galápagos Islands'],
    characteristics: {
      weight: 'Up to 3 tonnes',
      length: 'Wingspan up to 7 metres',
      lifespan: '40 years',
      diet: 'Zooplankton, fish larvae',
    },
    isFeatured: true,
  },
  {
    name: 'Snow Leopard',
    scientificName: 'Panthera uncia',
    habitat: 'Mountain',
    conservationStatus: 'Vulnerable',
    description: 'One of the world\'s most elusive big cats, the snow leopard inhabits the high mountain ranges of Central Asia. Its thick, pale-grey fur, enormous paws that act as snowshoes, and long tail used for balance and warmth make it a masterpiece of evolution for extreme altitude living.',
    image: 'https://images.unsplash.com/photo-1573108724029-4c46571d6490?w=1200',
    funFact: 'Snow leopards cannot roar — instead they communicate through chuffing, hissing, and a haunting wail called a "prusten."',
    foundAt: ['Scottish Highlands'],
    characteristics: {
      weight: '22-55 kg',
      length: 'Up to 1.3 metres (plus 1m tail)',
      lifespan: '15-18 years',
      diet: 'Blue sheep, ibex, marmots',
    },
    isFeatured: false,
  },
  {
    name: 'Jaguar',
    scientificName: 'Panthera onca',
    habitat: 'Forest',
    conservationStatus: 'Near Threatened',
    description: 'The largest cat in the Americas and the only big cat in the New World, the jaguar is a supreme apex predator of exceptional power. Unlike other big cats, jaguars love water and are strong swimmers — they regularly hunt caimans, capybaras, and even anacondas in the rivers of the Amazon basin.',
    image: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=1200',
    funFact: 'Jaguars kill with a unique method — they bite directly through the skull of their prey, rather than the throat like other big cats.',
    foundAt: ['Amazon River Basin'],
    characteristics: {
      weight: 'Up to 120 kg',
      length: 'Up to 1.85 metres',
      lifespan: '12-15 years',
      diet: 'Caimans, capybara, deer, fish',
    },
    isFeatured: false,
  },
  {
    name: 'Giant River Otter',
    scientificName: 'Pteronura brasiliensis',
    habitat: 'River',
    conservationStatus: 'Endangered',
    description: 'The largest otter in the world and one of the Amazon\'s most charismatic predators, the giant river otter hunts in coordinated family groups, communicating with a remarkable repertoire of vocalisations. They are fiercely territorial and have been observed successfully driving away caimans and even anacondas.',
    image: 'https://images.unsplash.com/photo-1614531341773-3bff8b7cb3fc?w=1200',
    funFact: 'Giant river otters are so vocal they have been recorded making at least 22 distinct sounds — from purrs and hums to screams and barks.',
    foundAt: ['Amazon River Basin'],
    characteristics: {
      weight: 'Up to 32 kg',
      length: 'Up to 1.8 metres',
      lifespan: '10-13 years',
      diet: 'Fish, crabs, snakes, small caimans',
    },
    isFeatured: false,
  },
  {
    name: 'Emperor Penguin',
    scientificName: 'Aptenodytes forsteri',
    habitat: 'Arctic',
    conservationStatus: 'Near Threatened',
    description: 'The tallest and heaviest of all penguin species, the emperor penguin is the only animal that breeds during the Antarctic winter — enduring temperatures of -60°C and winds of 200 km/h while incubating its egg on its feet. Male emperors fast for over four months, surviving entirely on their fat reserves while the females are at sea.',
    image: 'https://images.unsplash.com/photo-1517825738774-7de9363ef735?w=1200',
    funFact: 'Emperor penguins can dive to 565 metres and hold their breath for over 20 minutes — deeper and longer than any other bird.',
    foundAt: ['Antarctic Peninsula'],
    characteristics: {
      weight: 'Up to 45 kg',
      length: 'Up to 1.22 metres',
      lifespan: '20 years',
      diet: 'Fish, squid, krill',
    },
    isFeatured: true,
  },
  {
    name: 'Great White Shark',
    scientificName: 'Carcharodon carcharias',
    habitat: 'Ocean',
    conservationStatus: 'Vulnerable',
    description: 'The ocean\'s most iconic apex predator, the great white shark is a creature of extraordinary sensory capability. It can detect a single drop of blood from 5 kilometres away, sense the electromagnetic fields of prey buried under sand, and feel vibrations through special pressure-sensing organs along its lateral line.',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200',
    funFact: 'Great white sharks can detect electromagnetic fields as small as half a billionth of a volt — they can sense the heartbeat of a hidden animal.',
    foundAt: ['Great Barrier Reef', 'Galápagos Islands'],
    characteristics: {
      weight: 'Up to 3.3 tonnes',
      length: 'Up to 6 metres',
      lifespan: '70+ years',
      diet: 'Seals, sea lions, dolphins, fish',
    },
    isFeatured: false,
  },
]

const seedDB = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI)
    console.log('✅ MongoDB Connected')

    await Destination.deleteMany({})
    await Species.deleteMany({})
    console.log('🗑️  Existing data cleared')

    const createdDestinations = await Destination.insertMany(destinations)
    console.log(`🌍 ${createdDestinations.length} destinations seeded`)

    await Species.insertMany(species)
    console.log(`🐋 ${species.length} species seeded`)

    // Now seed tours with real destination IDs
    const bajaCal   = createdDestinations.find(d => d.name === 'Baja California')._id
    const reef      = createdDestinations.find(d => d.name === 'Great Barrier Reef')._id
    const amazon    = createdDestinations.find(d => d.name === 'Amazon River Basin')._id
    const norway    = createdDestinations.find(d => d.name === 'Norwegian Fjords')._id
    const serengeti = createdDestinations.find(d => d.name === 'Serengeti Plains')._id
    const galapagos = createdDestinations.find(d => d.name === 'Galápagos Islands')._id
    const antarctic = createdDestinations.find(d => d.name === 'Antarctic Peninsula')._id
    const scotland  = createdDestinations.find(d => d.name === 'Scottish Highlands')._id

    const tours = [
      {
        name: 'Blue Whale Migration Expedition',
        destination: bajaCal,
        description: 'Join marine biologists aboard a research vessel as you follow the ancient migration route of the blue whale through the nutrient-rich waters of Baja California. This is the single greatest wildlife spectacle on the planet.',
        duration: 7,
        maxGroupSize: 12,
        difficulty: 'Easy',
        pricePerPerson: 85000,
        category: 'Ocean Expedition',
        images: ['https://images.unsplash.com/photo-1568430462989-44163eb1752f?w=1200'],
        includes: ['Expert marine biologist guide', 'Research vessel accommodation', 'All meals on board', 'Snorkelling equipment', 'Underwater hydrophone sessions', 'Photography workshop'],
        excludes: ['International flights', 'Travel insurance', 'Alcoholic beverages', 'Personal expenses'],
        itinerary: [
          { day: 1, title: 'Arrival in La Paz', description: 'Transfer to vessel, welcome briefing, sunset dinner on deck.' },
          { day: 2, title: 'Sea of Cortez Crossing', description: 'Morning departure, dolphin and sea lion encounters along the way.' },
          { day: 3, title: 'First Blue Whale Encounter', description: 'Enter prime blue whale territory. Hydrophone listening sessions.' },
          { day: 4, title: 'Deep Water Dive', description: 'Snorkelling with whale sharks in Bahia de los Angeles.' },
          { day: 5, title: 'Grey Whale Lagoon', description: 'Visit Scammon Lagoon UNESCO sanctuary. Up-close grey whale interactions.' },
          { day: 6, title: 'Pacific Swell Day', description: 'Open ocean crossing. Seabird watching. Sperm whale territory.' },
          { day: 7, title: 'Return & Farewell', description: 'Morning wildlife watch, return to La Paz, farewell dinner.' },
        ],
        guideInfo: { name: 'Dr. Elena Vasquez', experience: '18 years marine biology, 400+ whale encounters' },
        isAvailable: true,
      },
      {
        name: 'Great Barrier Reef Dive Expedition',
        destination: reef,
        description: 'Spend five extraordinary days exploring the world\'s largest living structure — from shallow coral gardens alive with colour to deep walls where grey reef sharks patrol in the blue silence.',
        duration: 5,
        maxGroupSize: 10,
        difficulty: 'Moderate',
        pricePerPerson: 65000,
        category: 'Ocean Expedition',
        images: ['https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=1200'],
        includes: ['PADI dive master guide', 'All dive equipment', 'Live-aboard vessel', 'All meals', 'Up to 4 dives per day', 'Underwater photography guide'],
        excludes: ['Flights to Cairns', 'Travel insurance', 'Dive certification (if needed)', 'Alcohol'],
        itinerary: [
          { day: 1, title: 'Cairns Departure', description: 'Board live-aboard, afternoon orientation dive on Ribbon Reefs.' },
          { day: 2, title: 'Cod Hole & Coral Sea', description: 'Famous Cod Hole dive with giant potato cod. Night dive on coral wall.' },
          { day: 3, title: 'Osprey Reef', description: 'Shark dive with grey reefs and silvertips. Coral garden snorkelling.' },
          { day: 4, title: 'Turtle Highway', description: 'Green sea turtle breeding grounds. Manta ray cleaning station.' },
          { day: 5, title: 'Final Dives & Return', description: 'Dawn dive, morning snorkel, afternoon return to Cairns.' },
        ],
        guideInfo: { name: 'James Whitfield', experience: '12 years reef ecology, PADI Course Director' },
        isAvailable: true,
      },
      {
        name: 'Amazon Wilderness Immersion',
        destination: amazon,
        description: 'Eight days deep in the Amazon, navigating black-water tributaries by canoe, sleeping in jungle lodges, and tracking pink river dolphins, jaguars, and giant river otters with expert naturalist guides.',
        duration: 8,
        maxGroupSize: 8,
        difficulty: 'Moderate',
        pricePerPerson: 75000,
        category: 'River Journey',
        images: ['https://images.unsplash.com/photo-1614531341773-3bff8b7cb3fc?w=1200'],
        includes: ['Expert naturalist guide', 'Jungle lodge accommodation', 'All meals', 'Canoe expeditions', 'Night wildlife walks', 'Indigenous community visit'],
        excludes: ['Flights to Manaus', 'Travel insurance', 'Vaccinations', 'Personal items'],
        itinerary: [
          { day: 1, title: 'Manaus Arrival', description: 'Transfer to jungle lodge. Sunset river cruise.' },
          { day: 2, title: 'Meeting of the Waters', description: 'Witness the famous confluence of Rio Negro and Amazon. Pink dolphin encounter.' },
          { day: 3, title: 'Black Water Tributaries', description: 'Canoe deep into the igapó flooded forest. Caiman spotting at dusk.' },
          { day: 4, title: 'Jaguar Territory', description: 'Dawn walk in jaguar habitat. Camera trap data review with guide.' },
          { day: 5, title: 'Giant Otter Families', description: 'Stake-out at giant river otter territory. Piranha fishing at sunset.' },
          { day: 6, title: 'Canopy Walk', description: 'Suspension bridge walk above the forest canopy. Harpy eagle territory.' },
          { day: 7, title: 'Indigenous Visit', description: 'Visit to local Ribeirinhos community. Traditional fishing techniques.' },
          { day: 8, title: 'Return', description: 'Dawn bird walk, return journey to Manaus.' },
        ],
        guideInfo: { name: 'Carlos Mendoza', experience: '20 years Amazon ecology, born in Manaus' },
        isAvailable: true,
      },
      {
        name: 'Fjord Orca & Whale Safari',
        destination: norway,
        description: 'Winter in the Norwegian fjords brings one of nature\'s most dramatic spectacles — pods of orca and humpback whales hunting herring in the cold, dark waters beneath the northern lights.',
        duration: 6,
        maxGroupSize: 10,
        difficulty: 'Moderate',
        pricePerPerson: 90000,
        category: 'Ocean Expedition',
        images: ['https://images.unsplash.com/photo-1531366936337-7c912a4589a7?w=1200'],
        includes: ['Marine guide', 'Heated expedition vessel', 'Fjord accommodation', 'All meals', 'Snorkelling with orca option', 'Northern lights watch'],
        excludes: ['Flights to Tromsø', 'Travel insurance', 'Dry suit hire', 'Personal gear'],
        itinerary: [
          { day: 1, title: 'Tromsø Arrival', description: 'Board vessel, briefing on orca behaviour and safety.' },
          { day: 2, title: 'First Fjord Day', description: 'Enter Vestfjorden. Herring school location. First orca sightings.' },
          { day: 3, title: 'Orca Encounter', description: 'Snorkelling with orca pod option. Underwater photography session.' },
          { day: 4, title: 'Humpback Day', description: 'Humpback whale feeding frenzies. Hydrophone listening session.' },
          { day: 5, title: 'Northern Lights Cruise', description: 'Midnight on deck hoping for aurora. Sea eagle watching by day.' },
          { day: 6, title: 'Final Morning & Return', description: 'Dawn wildlife watch, return to Tromsø.' },
        ],
        guideInfo: { name: 'Ingrid Solberg', experience: '15 years Arctic marine research, Norwegian Institute' },
        isAvailable: true,
      },
      {
        name: 'Serengeti Great Migration Safari',
        destination: serengeti,
        description: 'Witness the most dramatic wildlife event on Earth — two million wildebeest crossing crocodile-filled rivers in a thundering, desperate, magnificent migration across the Serengeti.',
        duration: 7,
        maxGroupSize: 8,
        difficulty: 'Easy',
        pricePerPerson: 110000,
        category: 'Wildlife Safari',
        images: ['https://images.unsplash.com/photo-1516426122078-c23e76319801?w=1200'],
        includes: ['Expert safari guide', 'Luxury tented camp', 'All meals', 'Game drives twice daily', 'Hot air balloon safari', 'Maasai village visit'],
        excludes: ['Flights to Kilimanjaro', 'Travel insurance', 'Park fees', 'Tips'],
        itinerary: [
          { day: 1, title: 'Arusha Arrival', description: 'Transfer to Serengeti. Afternoon game drive.' },
          { day: 2, title: 'Central Serengeti', description: 'Lion pride tracking. Cheetah spotting on the plains.' },
          { day: 3, title: 'Migration River Crossing', description: 'Stake out at Mara River. Wildebeest crossing.' },
          { day: 4, title: 'Hot Air Balloon Dawn', description: 'Sunrise balloon flight over the plains. Bush breakfast.' },
          { day: 5, title: 'Big Five Day', description: 'Full day tracking all Big Five across the ecosystem.' },
          { day: 6, title: 'Ngorongoro Crater', description: 'Descend into the world\'s largest intact caldera.' },
          { day: 7, title: 'Return', description: 'Final dawn drive, transfer to Arusha.' },
        ],
        guideInfo: { name: 'Samuel Olepolos', experience: '22 years Serengeti, born Maasai tracker' },
        isAvailable: true,
      },
      {
        name: 'Galápagos Island Hopper',
        destination: galapagos,
        description: 'Ten days island-hopping through Darwin\'s living laboratory — snorkelling with marine iguanas, diving with hammerheads, and watching blue-footed boobies dance at arm\'s length.',
        duration: 10,
        maxGroupSize: 12,
        difficulty: 'Easy',
        pricePerPerson: 125000,
        category: 'Wildlife Safari',
        images: ['https://images.unsplash.com/photo-1544979590-37e9b47eb705?w=1200'],
        includes: ['Naturalist guide', 'Yacht accommodation', 'All meals', 'Snorkel equipment', 'Island landing permits', 'Darwin Research Station visit'],
        excludes: ['Flights to Quito', 'Galápagos entry fee', 'Travel insurance', 'Dive equipment'],
        itinerary: [
          { day: 1, title: 'Santa Cruz Island', description: 'Arrival, giant tortoise sanctuary, Darwin Station.' },
          { day: 2, title: 'North Seymour', description: 'Blue-footed booby colony, frigatebird nesting, sea lion beach.' },
          { day: 3, title: 'Española Island', description: 'Albatross colony, marine iguanas, blowhole.' },
          { day: 4, title: 'Marine Iguana Snorkel', description: 'Snorkelling with marine iguanas and sea turtles.' },
          { day: 5, title: 'Fernandina Island', description: 'Flightless cormorant. Largest marine iguana colony.' },
          { day: 6, title: 'Wolf & Darwin Islands', description: 'Advanced dive: hammerhead sharks, whale sharks.' },
          { day: 7, title: 'San Cristóbal', description: 'Sea lion colony. Kicker Rock dive.' },
          { day: 8, title: 'Bartolomé Island', description: 'Galápagos penguins. Volcanic landscape.' },
          { day: 9, title: 'Open Ocean', description: 'Manta ray feeding aggregation. Dolphin pods.' },
          { day: 10, title: 'Departure', description: 'Final morning snorkel, fly from Baltra.' },
        ],
        guideInfo: { name: 'Dr. Rosa Alvarado', experience: '16 years Galápagos research, Charles Darwin Foundation' },
        isAvailable: true,
      },
      {
        name: 'Antarctic Ice Expedition',
        destination: antarctic,
        description: 'The ultimate wilderness journey — fourteen days sailing to the most remote continent on Earth, where fin whales surface beside your ship, emperor penguins march in their thousands, and the silence is absolute.',
        duration: 14,
        maxGroupSize: 100,
        difficulty: 'Challenging',
        pricePerPerson: 250000,
        category: 'Arctic Expedition',
        images: ['https://images.unsplash.com/photo-1517825738774-7de9363ef735?w=1200'],
        includes: ['Expedition ship', 'Cabin accommodation', 'All meals', 'Zodiac landings', 'Expert lecture series', 'Polar plunge', 'Kayaking option'],
        excludes: ['Flights to Ushuaia', 'Travel insurance', 'Gratuities', 'Personal cold weather gear'],
        itinerary: [
          { day: 1, title: 'Ushuaia Embarkation', description: 'Board expedition ship, safety briefing, sail south.' },
          { day: 2, title: 'Drake Passage', description: 'Crossing the Drake. Seabird watching, albatross companions.' },
          { day: 3, title: 'Drake Passage', description: 'Lectures on Antarctic history and ecology. Cetacean watch.' },
          { day: 4, title: 'South Shetland Islands', description: 'First Antarctic landing. Chinstrap penguin colony.' },
          { day: 5, title: 'Antarctic Peninsula', description: 'Zodiac cruising among icebergs. Leopard seal encounters.' },
          { day: 6, title: 'Paradise Bay', description: 'Landing on the continent. Argentine research station visit.' },
          { day: 7, title: 'Fin Whale Alley', description: 'Gerlache Strait — prime fin whale and humpback territory.' },
          { day: 8, title: 'Emperor Penguin Colony', description: 'Full day with emperor penguin colony on sea ice.' },
          { day: 9, title: 'Weddell Sea', description: 'Kayaking among icebergs. Weddell seal haul-outs.' },
          { day: 10, title: 'Polar Plunge Day', description: 'Optional polar plunge. Orca sighting in Gerlache Strait.' },
          { day: 11, title: 'Deep South', description: 'Push towards Antarctic Circle. Midnight sun photography.' },
          { day: 12, title: 'Return North', description: 'Northbound crossing. Farewell dinner.' },
          { day: 13, title: 'Drake Passage', description: 'Return crossing. Recap lectures. Wildlife photography review.' },
          { day: 14, title: 'Ushuaia Return', description: 'Morning arrival, disembarkation.' },
        ],
        guideInfo: { name: 'Dr. Aleksei Petrov', experience: '25 years Antarctic research, Russian Arctic Institute' },
        isAvailable: true,
      },
      {
        name: 'Scottish Highlands Wildlife Trek',
        destination: scotland,
        description: 'Four days trekking through Britain\'s last great wilderness — tracking red deer through heather moorland, watching golden eagles soar above ancient glens, and catching otters at play on misty sea lochs.',
        duration: 4,
        maxGroupSize: 8,
        difficulty: 'Moderate',
        pricePerPerson: 45000,
        category: 'Mountain Trek',
        images: ['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200'],
        includes: ['Expert wildlife guide', 'Highland lodge accommodation', 'All meals', 'Binoculars provided', 'Wildlife tracking workshop', 'Whisky tasting evening'],
        excludes: ['Flights to Inverness', 'Travel insurance', 'Personal hiking gear', 'Tips'],
        itinerary: [
          { day: 1, title: 'Cairngorms Arrival', description: 'Inverness transfer, afternoon red squirrel walk in ancient Caledonian pine forest.' },
          { day: 2, title: 'Golden Eagle Day', description: 'Full day in golden eagle territory on the high tops. Red deer rut observation.' },
          { day: 3, title: 'Sea Loch & Otter Watch', description: 'Drive to west coast. Dawn otter watch on rocky shore. Harbour porpoise by boat.' },
          { day: 4, title: 'Osprey & Departure', description: 'Morning osprey watch at loch. Whisky distillery. Return to Inverness.' },
        ],
        guideInfo: { name: 'Fiona MacGregor', experience: '14 years Highland ecology, RSPB Scotland partner' },
        isAvailable: true,
      },
      {
        name: 'Humpback Whale Watching',
        destination: bajaCal,
        description: 'A focused three-day expedition to witness humpback whales in their winter breeding grounds — close enough to hear them breathe, watch them breach, and feel the water move as they pass beneath your boat.',
        duration: 3,
        maxGroupSize: 15,
        difficulty: 'Easy',
        pricePerPerson: 35000,
        category: 'Ocean Expedition',
        images: ['https://images.unsplash.com/photo-1614729939124-032d1e6c9945?w=1200'],
        includes: ['Marine guide', 'Small boat excursions', 'Hotel accommodation', 'Breakfast and lunch', 'Hydrophone session', 'Photo review workshop'],
        excludes: ['Flights to La Paz', 'Dinners', 'Travel insurance', 'Souvenirs'],
        itinerary: [
          { day: 1, title: 'La Paz Arrival', description: 'Afternoon orientation. Sunset briefing on humpback behaviour.' },
          { day: 2, title: 'Full Day Whale Watch', description: 'Dawn to dusk on the water. Humpback breaching, bubble-net feeding, song recording.' },
          { day: 3, title: 'Morning Session & Departure', description: 'Final morning whale watch, photo debrief, transfer to airport.' },
        ],
        guideInfo: { name: 'Marco Ibañez', experience: '10 years cetacean research, Baja specialist' },
        isAvailable: true,
      },
      {
        name: 'Manta Ray Snorkel Safari',
        destination: reef,
        description: 'Three magical days snorkelling with oceanic manta rays at their cleaning stations on the outer Great Barrier Reef — watching these gentle giants loop and spiral through crystal water as cleaner fish tend to them.',
        duration: 3,
        maxGroupSize: 10,
        difficulty: 'Easy',
        pricePerPerson: 40000,
        category: 'Ocean Expedition',
        images: ['https://images.unsplash.com/photo-1583212292454-1fe6229603b7?w=1200'],
        includes: ['Marine biologist guide', 'Day vessel from Cairns', 'All snorkel equipment', 'Lunch on board', 'Underwater photography tips', 'Marine ID workshop'],
        excludes: ['Flights to Cairns', 'Hotel accommodation', 'Travel insurance', 'Dinner'],
        itinerary: [
          { day: 1, title: 'Cairns Departure', description: 'Early boat, outer reef arrival, first manta encounter at cleaning station.' },
          { day: 2, title: 'Manta Aggregation', description: 'Full day at aggregation site. Up to 20 mantas. Night snorkel option.' },
          { day: 3, title: 'Turtle & Manta Morning', description: 'Final snorkel session, sea turtle encounters, return to Cairns.' },
        ],
        guideInfo: { name: 'Dr. Sarah Chen', experience: '11 years manta ray research, Marine Megafauna Foundation' },
        isAvailable: true,
      },
    ]

    await Tour.deleteMany({})
    await Tour.insertMany(tours)
    console.log(`🗺️  ${tours.length} tours seeded`)

    console.log('🌊 WildTide database seeded successfully!')
    process.exit(0)
  } catch (error) {
    console.error('❌ Seed failed:', error.message)
    process.exit(1)
  }
}

seedDB()